name:                cse230-code
version:             0.1.0.0
github:              "ucsd-cse230/fa23"
license:             MIT
author:              "Ranjit Jhala"
maintainer:          "jhala@cs.ucsd.edu"
copyright:           "2023 Ranjit Jhala"

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- process 
- directory 
- filepath
- containers
- QuickCheck
- unordered-containers
- mtl
- stm
- time
- random
- bytestring
- HTTP
- network-uri

library:
  source-dirs: src

executables:
  stm:
    main: stm.lhs
    source-dirs: src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
